//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2012-12-11 22:05:42 by HD
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.Practices.Unity;
using Apps.BLL;
using Apps.Common;
using Apps.Models;
using Apps.Models.Sys;
using System.Text;
using Apps.Web.Core;
using Apps.Locale;
using Apps.BLL.Sys;
using System;

namespace Apps.Web.Controllers
{
    public class SysAreasController : BaseController
    {

        public SysAreasBLL m_BLL = new SysAreasBLL();
        ValidationErrors errors = new ValidationErrors();


        //////[SupportFilter]
        public ActionResult Index()
        {
            
            return View();
        }
        [HttpPost]
        ////[SupportFilter(ActionName="Index")]
        public JsonResult GetList(string id)
        {
            if (id == null)
                id = "0";
            List<SysAreas> list = m_BLL._SysAreasRepository.FindList(a => a.ParentId  == id).ToList();
            var json = from r in list
                       select new
                       {
                        Id = r.Id,
                        KEY_Id = r.KEY_Id,
                        Name = r.Name,
		                ParentId = r.ParentId,
		                Sort = r.Sort,
		                Enable = r.Enable,
		                IsMunicipality = r.IsMunicipality,
		                IsHKMT = r.IsHKMT,
		                IsOther = r.IsOther,
                           CreateTime = r.CreateTime,
                           state = (m_BLL._SysAreasRepository.IsContains(a => a.ParentId == r.KEY_Id.ToString())) ? "closed" : "open"
                       };


            return Json(json);
        }
        [HttpPost]
        public JsonResult GetListByParentId(string Id)
        {
            if (Id == null)
                Id = "0";
            List<SysAreas> list = m_BLL._SysAreasRepository.FindList(a => a.ParentId == Id).ToList();
            StringBuilder sb = new StringBuilder("");
            foreach (var i in list)
            {
                sb.AppendFormat("<option value='{0}'>{1}</option>", i.KEY_Id, i.Name);
            }

            return Json(sb.ToString());
        }
        #region 创建
        //////[SupportFilter]
        public ActionResult Create(string KEY_Id)
        {
            
            SysAreas entity = new SysAreas()
            {
                ParentId = KEY_Id,
                Enable = "true"
            };
            return View(entity);
        }

        [HttpPost]
        //////[SupportFilter]
        public JsonResult Create(SysAreas model)
        {
            model.CreateTime = ResultHelper.NowTime.ToString("yyyy-MM-dd");
            if (model != null)
            {

                if (m_BLL._SysAreasRepository.Create(model))
                {
                    LogHandler.WriteServiceLog(GetUserId(), "KEY_Id" + model.KEY_Id + ",Name" + model.Name, "成功", "创建", "SysAreas");
                    return Json(JsonHandler.CreateMessage(1, Resource.InsertSucceed));
                }
                else
                {
                    string ErrorCol = errors.Error;
                    LogHandler.WriteServiceLog(GetUserId(), "KEY_Id" + model.KEY_Id + ",Name" + model.Name + "," + ErrorCol, "失败", "创建", "SysAreas");
                    return Json(JsonHandler.CreateMessage(0, Resource.InsertFail + ErrorCol));
                }
            }
            else
            {
                return Json(JsonHandler.CreateMessage(0, Resource.InsertFail));
            }
        }
        #endregion

        #region 修改
        //////[SupportFilter]
        public ActionResult Edit(string Id)
        {
            
            SysAreas entity = m_BLL._SysAreasRepository.Find(Convert.ToInt32(Id));
            return View(entity);
        }

        [HttpPost]
        //////[SupportFilter]
        public JsonResult Edit(SysAreas model)
        {
            if (model != null)
            {
                if (m_BLL._SysAreasRepository.Update(model))
                {
                    LogHandler.WriteServiceLog(GetUserId(), "Id" + model.Id + ",Name" + model.Name, "成功", "修改", "SysAreas");
                    return Json(JsonHandler.CreateMessage(1, Resource.EditSucceed));
                }
                else
                {
                    string ErrorCol = errors.Error;
                    LogHandler.WriteServiceLog(GetUserId(), "Id" + model.Id + ",Name" + model.Name + "," + ErrorCol, "失败", "修改", "SysAreas");
                    return Json(JsonHandler.CreateMessage(0, Resource.EditFail + ":"+ErrorCol));
                }
            }
            else
            {
                return Json(JsonHandler.CreateMessage(0, Resource.EditFail));
            }
        }
        #endregion

        #region 详细

        public ActionResult Details(string KEY_Id)
        {
            //获取父级
            List<SysAreas> list = m_BLL._SysAreasRepository.FindList(a => a.ParentId == "0").ToList();

            foreach (var model in list)
            {
                model.clildren = m_BLL._SysAreasRepository.FindList(a => a.ParentId == model.KEY_Id).ToList();
                foreach (var m in model.clildren)
                {
                    m.clildren = m_BLL._SysAreasRepository.FindList(a => a.ParentId == m.KEY_Id).ToList();
                }
            }

            return View(list);
        }

        #endregion

        #region 删除
        [HttpPost]
        //////[SupportFilter]
        public JsonResult Delete(string Id)
        {
            if (!string.IsNullOrWhiteSpace(Id))
            {
                SysAreas entity = m_BLL._SysAreasRepository.Find(Convert.ToInt32(Id));
                if (m_BLL._SysAreasRepository.Delete(entity.Id) >0)
                {
                    LogHandler.WriteServiceLog(GetUserId(), "Id:" + entity.Id, "成功", "删除", "SysAreas");
                    return Json(JsonHandler.CreateMessage(1, Resource.DeleteSucceed));
                }
                else
                {
                    string ErrorCol = errors.Error;
                    LogHandler.WriteServiceLog(GetUserId(), "Id" + entity.Id + "," + ErrorCol, "失败", "删除", "SysAreas");
                    return Json(JsonHandler.CreateMessage(0, Resource.DeleteFail + ErrorCol));
                }
            }
            else
            {
                return Json(JsonHandler.CreateMessage(0, Resource.DeleteFail));
            }


        }
        #endregion
    }
}
