//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models.WC
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using Apps.Models;
    using System.Collections.Generic;
    
    public partial class WC_MessageResponse
    {
        [Key]
        public int Id { get; set; }
        public string KEY_Id { get; set; }
        public string OfficalAccountId { get; set; }
        public string MessageRule { get; set; }
        public string Category { get; set; }
        public string MatchKey { get; set; }
        public string TextContent { get; set; }
        public string ImgTextContext { get; set; }
        public string ImgTextUrl { get; set; }
        public string ImgTextLink { get; set; }
        public string MeidaUrl { get; set; }
        public string MeidaLink { get; set; }
        public string Enable { get; set; }
        public string IsDefault { get; set; }
        public string Remark { get; set; }
        public string Sort { get; set; }
        public string CreateTime { get; set; }
        public string CreateBy { get; set; }
        public string ModifyTime { get; set; }
        public string ModifyBy { get; set; }
    }
}
