//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models.WC
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using Apps.Models;
    using System.Collections.Generic;
    
    public partial class WC_ResponseLog
    {
        [Key]
        public int Id { get; set; }
        public string KEY_Id { get; set; }
        public string OfficalAccountId { get; set; }
        public string OpenId { get; set; }
        public string RequestType { get; set; }
        public string RequestContent { get; set; }
        public string ResponseType { get; set; }
        public string ResponseContent { get; set; }
        public string CreateTime { get; set; }
        public string CreateBy { get; set; }
        public string ModifyTime { get; set; }
        public string ModifyBy { get; set; }
    }
}
