//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models.WC
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using Apps.Models;
    using System.Collections.Generic;
    
    public partial class WC_User
    {
        [Key]
        public int Id { get; set; }
        public string KEY_Id { get; set; }
        public string OpenId { get; set; }
        public string NickName { get; set; }
        public string Sex { get; set; }
        public string Language { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string HeadImgUrl { get; set; }
        public string SubscribeTime { get; set; }
        public string UnionId { get; set; }
        public string Remark { get; set; }
        public string GroupId { get; set; }
        public string TagidList { get; set; }
        public string Subscribe { get; set; }
        public string OfficalAccountId { get; set; }
    }
}
