//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MIS_WebIM_Message_Rec
    {
        [Key]
        public int Id { get; set; }

        public string KEY_Id { get; set; }
        public string MessageId { get; set; }
        public string receiver { get; set; }
        public string State { get; set; }
        public string RecDt { get; set; }
    
    }
}
