//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2012-12-11 21:56:03 by App
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Apps.Models.Sys
{

    public class SysAreas
    {

        [Key]
        public int Id { get; set; }
        public string KEY_Id { get; set; }
        [MaxWordsExpression(50)]
        [Display(Name = "名称")]
        public string Name { get; set; }

        [MaxWordsExpression(50)]
        [Display(Name = "上级ID")]
        public string ParentId { get; set; }

        [Display(Name = "排序")]
        public string Sort { get; set; }

        [Display(Name = "状态")]
        public string Enable { get; set; }

        [Display(Name = "创建时间")]
        public string CreateTime { get; set; }

        [Display(Name = "直辖市")]
        public string IsMunicipality { get; set; }

        [Display(Name = "特别行政区")]
        public string IsHKMT { get; set; }

        [Display(Name = "其他")]
        public string IsOther { get; set; }

        public string state { get; set; }

        public List<SysAreas> clildren { get; set; }


    }
}

