//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.ComponentModel.DataAnnotations;

    using System.ComponentModel;
    
    public partial class Flow_Seal
    {

        [Key]
        public int Id { get; set; }
        public string KEY_Id { get; set; }
        public string Path { get; set; }
        public string CreateTime { get; set; }
        public string Using { get; set; }
    }
}
