//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2012-12-11 22:12:12 by App
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Practices.Unity;
using Apps.Models;
using Apps.Common;
using Apps.BLL.Core;
using Apps.Models.MIS;
using Apps.Locale;
using Apps.DAL.MIS;

namespace Apps.BLL.MIS
{
    public partial class MIS_Article_CategoryBLL
    {
        public MIS_Article_CategoryRepository m_Rep;
        public MIS_Article_CategoryBLL()
        {
            m_Rep = new MIS_Article_CategoryRepository();
        }
        public List<MIS_Article_Category> GetList(string parentId)
        {
            IQueryable<MIS_Article_Category> queryData = null;
            queryData = m_Rep.FindList(a => a.ParentId == parentId).OrderBy(a => a.Sort);
            return queryData.ToList();
        }

        public List<MIS_Article_Category> GetListByParentId(string id)
        {
            List<MIS_Article_Category> query = m_Rep.FindList(a => a.ParentId == id).OrderBy(a => a.Sort).ToList();
            List<MIS_Article_Category> queryResult = new List<MIS_Article_Category>();
            foreach (MIS_Article_Category entity in query)
            {
                queryResult.Add(new MIS_Article_Category()
                {
                    Id = entity.Id,
                    Name = entity.Name,
                    ParentId = entity.ParentId,
                    Sort = entity.Sort,
                    ImgUrl = entity.ImgUrl,
                    BodyContent = entity.BodyContent,
                    ChannelId = entity.ChannelId == null ? "0" : entity.ChannelId,
                    CreateTime = entity.CreateTime,

                });
            }
            return queryResult;
        }

    }
}