//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models.Spl
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using Apps.Models;
    using System.Collections.Generic;
    
    public partial class Spl_Person
    {
        [Key]
        public int Id { get; set; }
        public string KEY_Id { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Age { get; set; }
        public string IDCard { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string CreateTime { get; set; }
        public string Region { get; set; }
        public string Category { get; set; }
    }
}
